# Generated by Django 2.1.7 on 2019-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avalaiability',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
