# Generated by Django 2.1.7 on 2019-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_superproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='superproduct',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
