# Generated by Django 2.1.7 on 2019-04-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_superproduct_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperProduct',
        ),
    ]
