# Generated by Django 2.1.7 on 2019-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_superproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avalaiability', models.BooleanField()),
                ('website', models.URLField(default='')),
            ],
        ),
    ]
